name: stream_chat_persistence
homepage: https://github.com/GetStream/stream-chat-flutter
description: Official Stream Chat Persistence library. Build your own chat experience using Dart and Flutter.
version: 5.1.0
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  drift: ^2.7.0
  flutter:
    sdk: flutter
  logging: ^1.0.1
  meta: ^1.3.0
  mutex: ^3.0.0
  path: ^1.8.0
  path_provider: ^2.0.11
  sqlite3_flutter_libs: ^0.5.11+1
  stream_chat: ^6.0.0

dev_dependencies:
  build_runner: ^2.3.0
  dart_code_metrics: ^5.7.2
  drift_dev: ^2.7.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  
dependency_overrides:
  analyzer: ^5.11.1